services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
    - key: DB_CONNECTION
      value: pgsql
    - key: DB_HOST
      value: ep-shy-mouse-ac3t7p0e-pooler.sa-east-1.aws.neon.tech
    - key: DB_PORT
      value: 5432
    - key: DB_DATABASE
      value: neondb
    - key: DB_USERNAME
      value: neondb_owner
    - key: DB_PASSWORD
      value: npg_TlqPQ2o9zRNF
    - key: APP_ENV
      value: production
    - key: APP_DEBUG
      value: false
    - key: APP_KEY
      generateValue: true